// Code generated by ent, DO NOT EDIT.

package investor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the investor type in the database.
	Label = "investor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldJoinedAt holds the string denoting the joined_at field in the database.
	FieldJoinedAt = "joined_at"
	// EdgeBids holds the string denoting the bids edge name in mutations.
	EdgeBids = "bids"
	// EdgeInvoices holds the string denoting the invoices edge name in mutations.
	EdgeInvoices = "invoices"
	// EdgeBalance holds the string denoting the balance edge name in mutations.
	EdgeBalance = "balance"
	// Table holds the table name of the investor in the database.
	Table = "investors"
	// BidsTable is the table that holds the bids relation/edge.
	BidsTable = "bids"
	// BidsInverseTable is the table name for the Bid entity.
	// It exists in this package in order to avoid circular dependency with the "bid" package.
	BidsInverseTable = "bids"
	// BidsColumn is the table column denoting the bids relation/edge.
	BidsColumn = "investor_bids"
	// InvoicesTable is the table that holds the invoices relation/edge. The primary key declared below.
	InvoicesTable = "investor_invoices"
	// InvoicesInverseTable is the table name for the Invoice entity.
	// It exists in this package in order to avoid circular dependency with the "invoice" package.
	InvoicesInverseTable = "invoices"
	// BalanceTable is the table that holds the balance relation/edge.
	BalanceTable = "investors"
	// BalanceInverseTable is the table name for the Balance entity.
	// It exists in this package in order to avoid circular dependency with the "balance" package.
	BalanceInverseTable = "balances"
	// BalanceColumn is the table column denoting the balance relation/edge.
	BalanceColumn = "investor_balance"
)

// Columns holds all SQL columns for investor fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldJoinedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "investors"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"investor_balance",
}

var (
	// InvoicesPrimaryKey and InvoicesColumn2 are the table columns denoting the
	// primary key for the invoices relation (M2M).
	InvoicesPrimaryKey = []string{"investor_id", "invoice_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultJoinedAt holds the default value on creation for the "joined_at" field.
	DefaultJoinedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Investor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByJoinedAt orders the results by the joined_at field.
func ByJoinedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedAt, opts...).ToFunc()
}

// ByBidsCount orders the results by bids count.
func ByBidsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBidsStep(), opts...)
	}
}

// ByBids orders the results by bids terms.
func ByBids(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBidsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInvoicesCount orders the results by invoices count.
func ByInvoicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInvoicesStep(), opts...)
	}
}

// ByInvoices orders the results by invoices terms.
func ByInvoices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvoicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBalanceField orders the results by balance field.
func ByBalanceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBalanceStep(), sql.OrderByField(field, opts...))
	}
}
func newBidsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BidsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BidsTable, BidsColumn),
	)
}
func newInvoicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvoicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, InvoicesTable, InvoicesPrimaryKey...),
	)
}
func newBalanceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BalanceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, BalanceTable, BalanceColumn),
	)
}
