// Code generated by ent, DO NOT EDIT.

package bid

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/tauki/invoiceexchange/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Bid {
	return predicate.Bid(sql.FieldLTE(FieldID, id))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldAmount, v))
}

// AcceptedAmount applies equality check predicate on the "accepted_amount" field. It's identical to AcceptedAmountEQ.
func AcceptedAmount(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldAcceptedAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Bid {
	return predicate.Bid(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Bid {
	return predicate.Bid(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Bid {
	return predicate.Bid(sql.FieldNotIn(FieldStatus, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.Bid {
	return predicate.Bid(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.Bid {
	return predicate.Bid(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldLTE(FieldAmount, v))
}

// AcceptedAmountEQ applies the EQ predicate on the "accepted_amount" field.
func AcceptedAmountEQ(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldAcceptedAmount, v))
}

// AcceptedAmountNEQ applies the NEQ predicate on the "accepted_amount" field.
func AcceptedAmountNEQ(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldNEQ(FieldAcceptedAmount, v))
}

// AcceptedAmountIn applies the In predicate on the "accepted_amount" field.
func AcceptedAmountIn(vs ...float64) predicate.Bid {
	return predicate.Bid(sql.FieldIn(FieldAcceptedAmount, vs...))
}

// AcceptedAmountNotIn applies the NotIn predicate on the "accepted_amount" field.
func AcceptedAmountNotIn(vs ...float64) predicate.Bid {
	return predicate.Bid(sql.FieldNotIn(FieldAcceptedAmount, vs...))
}

// AcceptedAmountGT applies the GT predicate on the "accepted_amount" field.
func AcceptedAmountGT(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldGT(FieldAcceptedAmount, v))
}

// AcceptedAmountGTE applies the GTE predicate on the "accepted_amount" field.
func AcceptedAmountGTE(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldGTE(FieldAcceptedAmount, v))
}

// AcceptedAmountLT applies the LT predicate on the "accepted_amount" field.
func AcceptedAmountLT(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldLT(FieldAcceptedAmount, v))
}

// AcceptedAmountLTE applies the LTE predicate on the "accepted_amount" field.
func AcceptedAmountLTE(v float64) predicate.Bid {
	return predicate.Bid(sql.FieldLTE(FieldAcceptedAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bid {
	return predicate.Bid(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasInvoice applies the HasEdge predicate on the "invoice" edge.
func HasInvoice() predicate.Bid {
	return predicate.Bid(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvoiceTable, InvoiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceWith applies the HasEdge predicate on the "invoice" edge with a given conditions (other predicates).
func HasInvoiceWith(preds ...predicate.Invoice) predicate.Bid {
	return predicate.Bid(func(s *sql.Selector) {
		step := newInvoiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvestor applies the HasEdge predicate on the "investor" edge.
func HasInvestor() predicate.Bid {
	return predicate.Bid(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvestorTable, InvestorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvestorWith applies the HasEdge predicate on the "investor" edge with a given conditions (other predicates).
func HasInvestorWith(preds ...predicate.Investor) predicate.Bid {
	return predicate.Bid(func(s *sql.Selector) {
		step := newInvestorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bid) predicate.Bid {
	return predicate.Bid(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bid) predicate.Bid {
	return predicate.Bid(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bid) predicate.Bid {
	return predicate.Bid(func(s *sql.Selector) {
		p(s.Not())
	})
}
