// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tauki/invoiceexchange/ent/balance"
	"github.com/tauki/invoiceexchange/ent/bid"
	"github.com/tauki/invoiceexchange/ent/investor"
	"github.com/tauki/invoiceexchange/ent/invoice"
	"github.com/tauki/invoiceexchange/ent/predicate"
)

// InvestorQuery is the builder for querying Investor entities.
type InvestorQuery struct {
	config
	ctx          *QueryContext
	order        []investor.OrderOption
	inters       []Interceptor
	predicates   []predicate.Investor
	withBids     *BidQuery
	withInvoices *InvoiceQuery
	withBalance  *BalanceQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InvestorQuery builder.
func (iq *InvestorQuery) Where(ps ...predicate.Investor) *InvestorQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit the number of records to be returned by this query.
func (iq *InvestorQuery) Limit(limit int) *InvestorQuery {
	iq.ctx.Limit = &limit
	return iq
}

// Offset to start from.
func (iq *InvestorQuery) Offset(offset int) *InvestorQuery {
	iq.ctx.Offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *InvestorQuery) Unique(unique bool) *InvestorQuery {
	iq.ctx.Unique = &unique
	return iq
}

// Order specifies how the records should be ordered.
func (iq *InvestorQuery) Order(o ...investor.OrderOption) *InvestorQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryBids chains the current query on the "bids" edge.
func (iq *InvestorQuery) QueryBids() *BidQuery {
	query := (&BidClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(investor.Table, investor.FieldID, selector),
			sqlgraph.To(bid.Table, bid.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, investor.BidsTable, investor.BidsColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInvoices chains the current query on the "invoices" edge.
func (iq *InvestorQuery) QueryInvoices() *InvoiceQuery {
	query := (&InvoiceClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(investor.Table, investor.FieldID, selector),
			sqlgraph.To(invoice.Table, invoice.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, investor.InvoicesTable, investor.InvoicesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBalance chains the current query on the "balance" edge.
func (iq *InvestorQuery) QueryBalance() *BalanceQuery {
	query := (&BalanceClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(investor.Table, investor.FieldID, selector),
			sqlgraph.To(balance.Table, balance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, investor.BalanceTable, investor.BalanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Investor entity from the query.
// Returns a *NotFoundError when no Investor was found.
func (iq *InvestorQuery) First(ctx context.Context) (*Investor, error) {
	nodes, err := iq.Limit(1).All(setContextOp(ctx, iq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{investor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *InvestorQuery) FirstX(ctx context.Context) *Investor {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Investor ID from the query.
// Returns a *NotFoundError when no Investor ID was found.
func (iq *InvestorQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = iq.Limit(1).IDs(setContextOp(ctx, iq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{investor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *InvestorQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Investor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Investor entity is found.
// Returns a *NotFoundError when no Investor entities are found.
func (iq *InvestorQuery) Only(ctx context.Context) (*Investor, error) {
	nodes, err := iq.Limit(2).All(setContextOp(ctx, iq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{investor.Label}
	default:
		return nil, &NotSingularError{investor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *InvestorQuery) OnlyX(ctx context.Context) *Investor {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Investor ID in the query.
// Returns a *NotSingularError when more than one Investor ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *InvestorQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = iq.Limit(2).IDs(setContextOp(ctx, iq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{investor.Label}
	default:
		err = &NotSingularError{investor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *InvestorQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Investors.
func (iq *InvestorQuery) All(ctx context.Context) ([]*Investor, error) {
	ctx = setContextOp(ctx, iq.ctx, "All")
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Investor, *InvestorQuery]()
	return withInterceptors[[]*Investor](ctx, iq, qr, iq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iq *InvestorQuery) AllX(ctx context.Context) []*Investor {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Investor IDs.
func (iq *InvestorQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if iq.ctx.Unique == nil && iq.path != nil {
		iq.Unique(true)
	}
	ctx = setContextOp(ctx, iq.ctx, "IDs")
	if err = iq.Select(investor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *InvestorQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *InvestorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iq.ctx, "Count")
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iq, querierCount[*InvestorQuery](), iq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iq *InvestorQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *InvestorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iq.ctx, "Exist")
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *InvestorQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InvestorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *InvestorQuery) Clone() *InvestorQuery {
	if iq == nil {
		return nil
	}
	return &InvestorQuery{
		config:       iq.config,
		ctx:          iq.ctx.Clone(),
		order:        append([]investor.OrderOption{}, iq.order...),
		inters:       append([]Interceptor{}, iq.inters...),
		predicates:   append([]predicate.Investor{}, iq.predicates...),
		withBids:     iq.withBids.Clone(),
		withInvoices: iq.withInvoices.Clone(),
		withBalance:  iq.withBalance.Clone(),
		// clone intermediate query.
		sql:  iq.sql.Clone(),
		path: iq.path,
	}
}

// WithBids tells the query-builder to eager-load the nodes that are connected to
// the "bids" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InvestorQuery) WithBids(opts ...func(*BidQuery)) *InvestorQuery {
	query := (&BidClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withBids = query
	return iq
}

// WithInvoices tells the query-builder to eager-load the nodes that are connected to
// the "invoices" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InvestorQuery) WithInvoices(opts ...func(*InvoiceQuery)) *InvestorQuery {
	query := (&InvoiceClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withInvoices = query
	return iq
}

// WithBalance tells the query-builder to eager-load the nodes that are connected to
// the "balance" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InvestorQuery) WithBalance(opts ...func(*BalanceQuery)) *InvestorQuery {
	query := (&BalanceClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withBalance = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Investor.Query().
//		GroupBy(investor.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *InvestorQuery) GroupBy(field string, fields ...string) *InvestorGroupBy {
	iq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InvestorGroupBy{build: iq}
	grbuild.flds = &iq.ctx.Fields
	grbuild.label = investor.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Investor.Query().
//		Select(investor.FieldName).
//		Scan(ctx, &v)
func (iq *InvestorQuery) Select(fields ...string) *InvestorSelect {
	iq.ctx.Fields = append(iq.ctx.Fields, fields...)
	sbuild := &InvestorSelect{InvestorQuery: iq}
	sbuild.label = investor.Label
	sbuild.flds, sbuild.scan = &iq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InvestorSelect configured with the given aggregations.
func (iq *InvestorQuery) Aggregate(fns ...AggregateFunc) *InvestorSelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *InvestorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iq); err != nil {
				return err
			}
		}
	}
	for _, f := range iq.ctx.Fields {
		if !investor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *InvestorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Investor, error) {
	var (
		nodes       = []*Investor{}
		withFKs     = iq.withFKs
		_spec       = iq.querySpec()
		loadedTypes = [3]bool{
			iq.withBids != nil,
			iq.withInvoices != nil,
			iq.withBalance != nil,
		}
	)
	if iq.withBalance != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, investor.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Investor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Investor{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withBids; query != nil {
		if err := iq.loadBids(ctx, query, nodes,
			func(n *Investor) { n.Edges.Bids = []*Bid{} },
			func(n *Investor, e *Bid) { n.Edges.Bids = append(n.Edges.Bids, e) }); err != nil {
			return nil, err
		}
	}
	if query := iq.withInvoices; query != nil {
		if err := iq.loadInvoices(ctx, query, nodes,
			func(n *Investor) { n.Edges.Invoices = []*Invoice{} },
			func(n *Investor, e *Invoice) { n.Edges.Invoices = append(n.Edges.Invoices, e) }); err != nil {
			return nil, err
		}
	}
	if query := iq.withBalance; query != nil {
		if err := iq.loadBalance(ctx, query, nodes, nil,
			func(n *Investor, e *Balance) { n.Edges.Balance = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *InvestorQuery) loadBids(ctx context.Context, query *BidQuery, nodes []*Investor, init func(*Investor), assign func(*Investor, *Bid)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Investor)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Bid(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(investor.BidsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.investor_bids
		if fk == nil {
			return fmt.Errorf(`foreign-key "investor_bids" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "investor_bids" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (iq *InvestorQuery) loadInvoices(ctx context.Context, query *InvoiceQuery, nodes []*Investor, init func(*Investor), assign func(*Investor, *Invoice)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Investor)
	nids := make(map[uuid.UUID]map[*Investor]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(investor.InvoicesTable)
		s.Join(joinT).On(s.C(invoice.FieldID), joinT.C(investor.InvoicesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(investor.InvoicesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(investor.InvoicesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Investor]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Invoice](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "invoices" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (iq *InvestorQuery) loadBalance(ctx context.Context, query *BalanceQuery, nodes []*Investor, init func(*Investor), assign func(*Investor, *Balance)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Investor)
	for i := range nodes {
		if nodes[i].investor_balance == nil {
			continue
		}
		fk := *nodes[i].investor_balance
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(balance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "investor_balance" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (iq *InvestorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	_spec.Node.Columns = iq.ctx.Fields
	if len(iq.ctx.Fields) > 0 {
		_spec.Unique = iq.ctx.Unique != nil && *iq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *InvestorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(investor.Table, investor.Columns, sqlgraph.NewFieldSpec(investor.FieldID, field.TypeUUID))
	_spec.From = iq.sql
	if unique := iq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iq.path != nil {
		_spec.Unique = true
	}
	if fields := iq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, investor.FieldID)
		for i := range fields {
			if fields[i] != investor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *InvestorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(investor.Table)
	columns := iq.ctx.Fields
	if len(columns) == 0 {
		columns = investor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.ctx.Unique != nil && *iq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InvestorGroupBy is the group-by builder for Investor entities.
type InvestorGroupBy struct {
	selector
	build *InvestorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *InvestorGroupBy) Aggregate(fns ...AggregateFunc) *InvestorGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the selector query and scans the result into the given value.
func (igb *InvestorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, igb.build.ctx, "GroupBy")
	if err := igb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvestorQuery, *InvestorGroupBy](ctx, igb.build, igb, igb.build.inters, v)
}

func (igb *InvestorGroupBy) sqlScan(ctx context.Context, root *InvestorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*igb.flds)+len(igb.fns))
		for _, f := range *igb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*igb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InvestorSelect is the builder for selecting fields of Investor entities.
type InvestorSelect struct {
	*InvestorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *InvestorSelect) Aggregate(fns ...AggregateFunc) *InvestorSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *InvestorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, "Select")
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvestorQuery, *InvestorSelect](ctx, is.InvestorQuery, is, is.inters, v)
}

func (is *InvestorSelect) sqlScan(ctx context.Context, root *InvestorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
