// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tauki/invoiceexchange/ent/bid"
	"github.com/tauki/invoiceexchange/ent/investor"
	"github.com/tauki/invoiceexchange/ent/invoice"
	"github.com/tauki/invoiceexchange/ent/invoiceitem"
	"github.com/tauki/invoiceexchange/ent/issuer"
)

// InvoiceCreate is the builder for creating a Invoice entity.
type InvoiceCreate struct {
	config
	mutation *InvoiceMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (ic *InvoiceCreate) SetStatus(i invoice.Status) *InvoiceCreate {
	ic.mutation.SetStatus(i)
	return ic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableStatus(i *invoice.Status) *InvoiceCreate {
	if i != nil {
		ic.SetStatus(*i)
	}
	return ic
}

// SetAskingPrice sets the "asking_price" field.
func (ic *InvoiceCreate) SetAskingPrice(f float64) *InvoiceCreate {
	ic.mutation.SetAskingPrice(f)
	return ic
}

// SetNillableAskingPrice sets the "asking_price" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableAskingPrice(f *float64) *InvoiceCreate {
	if f != nil {
		ic.SetAskingPrice(*f)
	}
	return ic
}

// SetIsLocked sets the "is_locked" field.
func (ic *InvoiceCreate) SetIsLocked(b bool) *InvoiceCreate {
	ic.mutation.SetIsLocked(b)
	return ic
}

// SetNillableIsLocked sets the "is_locked" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableIsLocked(b *bool) *InvoiceCreate {
	if b != nil {
		ic.SetIsLocked(*b)
	}
	return ic
}

// SetIsApproved sets the "is_approved" field.
func (ic *InvoiceCreate) SetIsApproved(b bool) *InvoiceCreate {
	ic.mutation.SetIsApproved(b)
	return ic
}

// SetNillableIsApproved sets the "is_approved" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableIsApproved(b *bool) *InvoiceCreate {
	if b != nil {
		ic.SetIsApproved(*b)
	}
	return ic
}

// SetInvoiceNumber sets the "invoice_number" field.
func (ic *InvoiceCreate) SetInvoiceNumber(s string) *InvoiceCreate {
	ic.mutation.SetInvoiceNumber(s)
	return ic
}

// SetInvoiceDate sets the "invoice_date" field.
func (ic *InvoiceCreate) SetInvoiceDate(t time.Time) *InvoiceCreate {
	ic.mutation.SetInvoiceDate(t)
	return ic
}

// SetDueDate sets the "due_date" field.
func (ic *InvoiceCreate) SetDueDate(t time.Time) *InvoiceCreate {
	ic.mutation.SetDueDate(t)
	return ic
}

// SetAmountDue sets the "amount_due" field.
func (ic *InvoiceCreate) SetAmountDue(f float64) *InvoiceCreate {
	ic.mutation.SetAmountDue(f)
	return ic
}

// SetCustomerName sets the "customer_name" field.
func (ic *InvoiceCreate) SetCustomerName(s string) *InvoiceCreate {
	ic.mutation.SetCustomerName(s)
	return ic
}

// SetReference sets the "reference" field.
func (ic *InvoiceCreate) SetReference(s string) *InvoiceCreate {
	ic.mutation.SetReference(s)
	return ic
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableReference(s *string) *InvoiceCreate {
	if s != nil {
		ic.SetReference(*s)
	}
	return ic
}

// SetCompanyName sets the "company_name" field.
func (ic *InvoiceCreate) SetCompanyName(s string) *InvoiceCreate {
	ic.mutation.SetCompanyName(s)
	return ic
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableCompanyName(s *string) *InvoiceCreate {
	if s != nil {
		ic.SetCompanyName(*s)
	}
	return ic
}

// SetCurrency sets the "currency" field.
func (ic *InvoiceCreate) SetCurrency(s string) *InvoiceCreate {
	ic.mutation.SetCurrency(s)
	return ic
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableCurrency(s *string) *InvoiceCreate {
	if s != nil {
		ic.SetCurrency(*s)
	}
	return ic
}

// SetTotalAmount sets the "total_amount" field.
func (ic *InvoiceCreate) SetTotalAmount(f float64) *InvoiceCreate {
	ic.mutation.SetTotalAmount(f)
	return ic
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableTotalAmount(f *float64) *InvoiceCreate {
	if f != nil {
		ic.SetTotalAmount(*f)
	}
	return ic
}

// SetTotalVat sets the "total_vat" field.
func (ic *InvoiceCreate) SetTotalVat(f float64) *InvoiceCreate {
	ic.mutation.SetTotalVat(f)
	return ic
}

// SetNillableTotalVat sets the "total_vat" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableTotalVat(f *float64) *InvoiceCreate {
	if f != nil {
		ic.SetTotalVat(*f)
	}
	return ic
}

// SetCreatedAt sets the "created_at" field.
func (ic *InvoiceCreate) SetCreatedAt(t time.Time) *InvoiceCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableCreatedAt(t *time.Time) *InvoiceCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetID sets the "id" field.
func (ic *InvoiceCreate) SetID(u uuid.UUID) *InvoiceCreate {
	ic.mutation.SetID(u)
	return ic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableID(u *uuid.UUID) *InvoiceCreate {
	if u != nil {
		ic.SetID(*u)
	}
	return ic
}

// AddItemIDs adds the "items" edge to the InvoiceItem entity by IDs.
func (ic *InvoiceCreate) AddItemIDs(ids ...uuid.UUID) *InvoiceCreate {
	ic.mutation.AddItemIDs(ids...)
	return ic
}

// AddItems adds the "items" edges to the InvoiceItem entity.
func (ic *InvoiceCreate) AddItems(i ...*InvoiceItem) *InvoiceCreate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ic.AddItemIDs(ids...)
}

// AddBidIDs adds the "bids" edge to the Bid entity by IDs.
func (ic *InvoiceCreate) AddBidIDs(ids ...uuid.UUID) *InvoiceCreate {
	ic.mutation.AddBidIDs(ids...)
	return ic
}

// AddBids adds the "bids" edges to the Bid entity.
func (ic *InvoiceCreate) AddBids(b ...*Bid) *InvoiceCreate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return ic.AddBidIDs(ids...)
}

// SetIssuerID sets the "issuer" edge to the Issuer entity by ID.
func (ic *InvoiceCreate) SetIssuerID(id uuid.UUID) *InvoiceCreate {
	ic.mutation.SetIssuerID(id)
	return ic
}

// SetIssuer sets the "issuer" edge to the Issuer entity.
func (ic *InvoiceCreate) SetIssuer(i *Issuer) *InvoiceCreate {
	return ic.SetIssuerID(i.ID)
}

// AddInvestorIDs adds the "investor" edge to the Investor entity by IDs.
func (ic *InvoiceCreate) AddInvestorIDs(ids ...uuid.UUID) *InvoiceCreate {
	ic.mutation.AddInvestorIDs(ids...)
	return ic
}

// AddInvestor adds the "investor" edges to the Investor entity.
func (ic *InvoiceCreate) AddInvestor(i ...*Investor) *InvoiceCreate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ic.AddInvestorIDs(ids...)
}

// Mutation returns the InvoiceMutation object of the builder.
func (ic *InvoiceCreate) Mutation() *InvoiceMutation {
	return ic.mutation
}

// Save creates the Invoice in the database.
func (ic *InvoiceCreate) Save(ctx context.Context) (*Invoice, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InvoiceCreate) SaveX(ctx context.Context) *Invoice {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InvoiceCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InvoiceCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *InvoiceCreate) defaults() {
	if _, ok := ic.mutation.Status(); !ok {
		v := invoice.DefaultStatus
		ic.mutation.SetStatus(v)
	}
	if _, ok := ic.mutation.AskingPrice(); !ok {
		v := invoice.DefaultAskingPrice
		ic.mutation.SetAskingPrice(v)
	}
	if _, ok := ic.mutation.IsLocked(); !ok {
		v := invoice.DefaultIsLocked
		ic.mutation.SetIsLocked(v)
	}
	if _, ok := ic.mutation.IsApproved(); !ok {
		v := invoice.DefaultIsApproved
		ic.mutation.SetIsApproved(v)
	}
	if _, ok := ic.mutation.Currency(); !ok {
		v := invoice.DefaultCurrency
		ic.mutation.SetCurrency(v)
	}
	if _, ok := ic.mutation.TotalAmount(); !ok {
		v := invoice.DefaultTotalAmount
		ic.mutation.SetTotalAmount(v)
	}
	if _, ok := ic.mutation.TotalVat(); !ok {
		v := invoice.DefaultTotalVat
		ic.mutation.SetTotalVat(v)
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := invoice.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.ID(); !ok {
		v := invoice.DefaultID()
		ic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InvoiceCreate) check() error {
	if _, ok := ic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Invoice.status"`)}
	}
	if v, ok := ic.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if _, ok := ic.mutation.AskingPrice(); !ok {
		return &ValidationError{Name: "asking_price", err: errors.New(`ent: missing required field "Invoice.asking_price"`)}
	}
	if _, ok := ic.mutation.IsLocked(); !ok {
		return &ValidationError{Name: "is_locked", err: errors.New(`ent: missing required field "Invoice.is_locked"`)}
	}
	if _, ok := ic.mutation.IsApproved(); !ok {
		return &ValidationError{Name: "is_approved", err: errors.New(`ent: missing required field "Invoice.is_approved"`)}
	}
	if _, ok := ic.mutation.InvoiceNumber(); !ok {
		return &ValidationError{Name: "invoice_number", err: errors.New(`ent: missing required field "Invoice.invoice_number"`)}
	}
	if _, ok := ic.mutation.InvoiceDate(); !ok {
		return &ValidationError{Name: "invoice_date", err: errors.New(`ent: missing required field "Invoice.invoice_date"`)}
	}
	if _, ok := ic.mutation.DueDate(); !ok {
		return &ValidationError{Name: "due_date", err: errors.New(`ent: missing required field "Invoice.due_date"`)}
	}
	if _, ok := ic.mutation.AmountDue(); !ok {
		return &ValidationError{Name: "amount_due", err: errors.New(`ent: missing required field "Invoice.amount_due"`)}
	}
	if _, ok := ic.mutation.CustomerName(); !ok {
		return &ValidationError{Name: "customer_name", err: errors.New(`ent: missing required field "Invoice.customer_name"`)}
	}
	if _, ok := ic.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Invoice.currency"`)}
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Invoice.created_at"`)}
	}
	if _, ok := ic.mutation.IssuerID(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required edge "Invoice.issuer"`)}
	}
	return nil
}

func (ic *InvoiceCreate) sqlSave(ctx context.Context) (*Invoice, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InvoiceCreate) createSpec() (*Invoice, *sqlgraph.CreateSpec) {
	var (
		_node = &Invoice{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(invoice.Table, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUUID))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ic.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ic.mutation.AskingPrice(); ok {
		_spec.SetField(invoice.FieldAskingPrice, field.TypeFloat64, value)
		_node.AskingPrice = value
	}
	if value, ok := ic.mutation.IsLocked(); ok {
		_spec.SetField(invoice.FieldIsLocked, field.TypeBool, value)
		_node.IsLocked = value
	}
	if value, ok := ic.mutation.IsApproved(); ok {
		_spec.SetField(invoice.FieldIsApproved, field.TypeBool, value)
		_node.IsApproved = value
	}
	if value, ok := ic.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoice.FieldInvoiceNumber, field.TypeString, value)
		_node.InvoiceNumber = value
	}
	if value, ok := ic.mutation.InvoiceDate(); ok {
		_spec.SetField(invoice.FieldInvoiceDate, field.TypeTime, value)
		_node.InvoiceDate = value
	}
	if value, ok := ic.mutation.DueDate(); ok {
		_spec.SetField(invoice.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if value, ok := ic.mutation.AmountDue(); ok {
		_spec.SetField(invoice.FieldAmountDue, field.TypeFloat64, value)
		_node.AmountDue = value
	}
	if value, ok := ic.mutation.CustomerName(); ok {
		_spec.SetField(invoice.FieldCustomerName, field.TypeString, value)
		_node.CustomerName = value
	}
	if value, ok := ic.mutation.Reference(); ok {
		_spec.SetField(invoice.FieldReference, field.TypeString, value)
		_node.Reference = value
	}
	if value, ok := ic.mutation.CompanyName(); ok {
		_spec.SetField(invoice.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := ic.mutation.Currency(); ok {
		_spec.SetField(invoice.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := ic.mutation.TotalAmount(); ok {
		_spec.SetField(invoice.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := ic.mutation.TotalVat(); ok {
		_spec.SetField(invoice.FieldTotalVat, field.TypeFloat64, value)
		_node.TotalVat = value
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(invoice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := ic.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.BidsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.BidsTable,
			Columns: []string{invoice.BidsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bid.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.IssuerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.IssuerTable,
			Columns: []string{invoice.IssuerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issuer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.issuer_invoices = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.InvestorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   invoice.InvestorTable,
			Columns: invoice.InvestorPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InvoiceCreateBulk is the builder for creating many Invoice entities in bulk.
type InvoiceCreateBulk struct {
	config
	builders []*InvoiceCreate
}

// Save creates the Invoice entities in the database.
func (icb *InvoiceCreateBulk) Save(ctx context.Context) ([]*Invoice, error) {
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Invoice, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InvoiceCreateBulk) SaveX(ctx context.Context) []*Invoice {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InvoiceCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InvoiceCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
