// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tauki/invoiceexchange/ent/invoiceitem"
	"github.com/tauki/invoiceexchange/ent/predicate"
)

// InvoiceItemDelete is the builder for deleting a InvoiceItem entity.
type InvoiceItemDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceItemMutation
}

// Where appends a list predicates to the InvoiceItemDelete builder.
func (iid *InvoiceItemDelete) Where(ps ...predicate.InvoiceItem) *InvoiceItemDelete {
	iid.mutation.Where(ps...)
	return iid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iid *InvoiceItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, iid.sqlExec, iid.mutation, iid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (iid *InvoiceItemDelete) ExecX(ctx context.Context) int {
	n, err := iid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iid *InvoiceItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoiceitem.Table, sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeUUID))
	if ps := iid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, iid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	iid.mutation.done = true
	return affected, err
}

// InvoiceItemDeleteOne is the builder for deleting a single InvoiceItem entity.
type InvoiceItemDeleteOne struct {
	iid *InvoiceItemDelete
}

// Where appends a list predicates to the InvoiceItemDelete builder.
func (iido *InvoiceItemDeleteOne) Where(ps ...predicate.InvoiceItem) *InvoiceItemDeleteOne {
	iido.iid.mutation.Where(ps...)
	return iido
}

// Exec executes the deletion query.
func (iido *InvoiceItemDeleteOne) Exec(ctx context.Context) error {
	n, err := iido.iid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoiceitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iido *InvoiceItemDeleteOne) ExecX(ctx context.Context) {
	if err := iido.Exec(ctx); err != nil {
		panic(err)
	}
}
