// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tauki/invoiceexchange/ent/balance"
	"github.com/tauki/invoiceexchange/ent/invoice"
	"github.com/tauki/invoiceexchange/ent/issuer"
	"github.com/tauki/invoiceexchange/ent/predicate"
)

// IssuerUpdate is the builder for updating Issuer entities.
type IssuerUpdate struct {
	config
	hooks    []Hook
	mutation *IssuerMutation
}

// Where appends a list predicates to the IssuerUpdate builder.
func (iu *IssuerUpdate) Where(ps ...predicate.Issuer) *IssuerUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetName sets the "name" field.
func (iu *IssuerUpdate) SetName(s string) *IssuerUpdate {
	iu.mutation.SetName(s)
	return iu
}

// AddInvoiceIDs adds the "invoices" edge to the Invoice entity by IDs.
func (iu *IssuerUpdate) AddInvoiceIDs(ids ...uuid.UUID) *IssuerUpdate {
	iu.mutation.AddInvoiceIDs(ids...)
	return iu
}

// AddInvoices adds the "invoices" edges to the Invoice entity.
func (iu *IssuerUpdate) AddInvoices(i ...*Invoice) *IssuerUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iu.AddInvoiceIDs(ids...)
}

// SetBalanceID sets the "balance" edge to the Balance entity by ID.
func (iu *IssuerUpdate) SetBalanceID(id uuid.UUID) *IssuerUpdate {
	iu.mutation.SetBalanceID(id)
	return iu
}

// SetBalance sets the "balance" edge to the Balance entity.
func (iu *IssuerUpdate) SetBalance(b *Balance) *IssuerUpdate {
	return iu.SetBalanceID(b.ID)
}

// Mutation returns the IssuerMutation object of the builder.
func (iu *IssuerUpdate) Mutation() *IssuerMutation {
	return iu.mutation
}

// ClearInvoices clears all "invoices" edges to the Invoice entity.
func (iu *IssuerUpdate) ClearInvoices() *IssuerUpdate {
	iu.mutation.ClearInvoices()
	return iu
}

// RemoveInvoiceIDs removes the "invoices" edge to Invoice entities by IDs.
func (iu *IssuerUpdate) RemoveInvoiceIDs(ids ...uuid.UUID) *IssuerUpdate {
	iu.mutation.RemoveInvoiceIDs(ids...)
	return iu
}

// RemoveInvoices removes "invoices" edges to Invoice entities.
func (iu *IssuerUpdate) RemoveInvoices(i ...*Invoice) *IssuerUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iu.RemoveInvoiceIDs(ids...)
}

// ClearBalance clears the "balance" edge to the Balance entity.
func (iu *IssuerUpdate) ClearBalance() *IssuerUpdate {
	iu.mutation.ClearBalance()
	return iu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *IssuerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *IssuerUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *IssuerUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *IssuerUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *IssuerUpdate) check() error {
	if _, ok := iu.mutation.BalanceID(); iu.mutation.BalanceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Issuer.balance"`)
	}
	return nil
}

func (iu *IssuerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(issuer.Table, issuer.Columns, sqlgraph.NewFieldSpec(issuer.FieldID, field.TypeUUID))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.Name(); ok {
		_spec.SetField(issuer.FieldName, field.TypeString, value)
	}
	if iu.mutation.InvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issuer.InvoicesTable,
			Columns: []string{issuer.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.RemovedInvoicesIDs(); len(nodes) > 0 && !iu.mutation.InvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issuer.InvoicesTable,
			Columns: []string{issuer.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.InvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issuer.InvoicesTable,
			Columns: []string{issuer.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iu.mutation.BalanceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   issuer.BalanceTable,
			Columns: []string{issuer.BalanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balance.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.BalanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   issuer.BalanceTable,
			Columns: []string{issuer.BalanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issuer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// IssuerUpdateOne is the builder for updating a single Issuer entity.
type IssuerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IssuerMutation
}

// SetName sets the "name" field.
func (iuo *IssuerUpdateOne) SetName(s string) *IssuerUpdateOne {
	iuo.mutation.SetName(s)
	return iuo
}

// AddInvoiceIDs adds the "invoices" edge to the Invoice entity by IDs.
func (iuo *IssuerUpdateOne) AddInvoiceIDs(ids ...uuid.UUID) *IssuerUpdateOne {
	iuo.mutation.AddInvoiceIDs(ids...)
	return iuo
}

// AddInvoices adds the "invoices" edges to the Invoice entity.
func (iuo *IssuerUpdateOne) AddInvoices(i ...*Invoice) *IssuerUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iuo.AddInvoiceIDs(ids...)
}

// SetBalanceID sets the "balance" edge to the Balance entity by ID.
func (iuo *IssuerUpdateOne) SetBalanceID(id uuid.UUID) *IssuerUpdateOne {
	iuo.mutation.SetBalanceID(id)
	return iuo
}

// SetBalance sets the "balance" edge to the Balance entity.
func (iuo *IssuerUpdateOne) SetBalance(b *Balance) *IssuerUpdateOne {
	return iuo.SetBalanceID(b.ID)
}

// Mutation returns the IssuerMutation object of the builder.
func (iuo *IssuerUpdateOne) Mutation() *IssuerMutation {
	return iuo.mutation
}

// ClearInvoices clears all "invoices" edges to the Invoice entity.
func (iuo *IssuerUpdateOne) ClearInvoices() *IssuerUpdateOne {
	iuo.mutation.ClearInvoices()
	return iuo
}

// RemoveInvoiceIDs removes the "invoices" edge to Invoice entities by IDs.
func (iuo *IssuerUpdateOne) RemoveInvoiceIDs(ids ...uuid.UUID) *IssuerUpdateOne {
	iuo.mutation.RemoveInvoiceIDs(ids...)
	return iuo
}

// RemoveInvoices removes "invoices" edges to Invoice entities.
func (iuo *IssuerUpdateOne) RemoveInvoices(i ...*Invoice) *IssuerUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iuo.RemoveInvoiceIDs(ids...)
}

// ClearBalance clears the "balance" edge to the Balance entity.
func (iuo *IssuerUpdateOne) ClearBalance() *IssuerUpdateOne {
	iuo.mutation.ClearBalance()
	return iuo
}

// Where appends a list predicates to the IssuerUpdate builder.
func (iuo *IssuerUpdateOne) Where(ps ...predicate.Issuer) *IssuerUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *IssuerUpdateOne) Select(field string, fields ...string) *IssuerUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Issuer entity.
func (iuo *IssuerUpdateOne) Save(ctx context.Context) (*Issuer, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *IssuerUpdateOne) SaveX(ctx context.Context) *Issuer {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *IssuerUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *IssuerUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *IssuerUpdateOne) check() error {
	if _, ok := iuo.mutation.BalanceID(); iuo.mutation.BalanceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Issuer.balance"`)
	}
	return nil
}

func (iuo *IssuerUpdateOne) sqlSave(ctx context.Context) (_node *Issuer, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(issuer.Table, issuer.Columns, sqlgraph.NewFieldSpec(issuer.FieldID, field.TypeUUID))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Issuer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issuer.FieldID)
		for _, f := range fields {
			if !issuer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != issuer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.Name(); ok {
		_spec.SetField(issuer.FieldName, field.TypeString, value)
	}
	if iuo.mutation.InvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issuer.InvoicesTable,
			Columns: []string{issuer.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.RemovedInvoicesIDs(); len(nodes) > 0 && !iuo.mutation.InvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issuer.InvoicesTable,
			Columns: []string{issuer.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.InvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issuer.InvoicesTable,
			Columns: []string{issuer.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iuo.mutation.BalanceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   issuer.BalanceTable,
			Columns: []string{issuer.BalanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balance.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.BalanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   issuer.BalanceTable,
			Columns: []string{issuer.BalanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Issuer{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issuer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
