// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tauki/invoiceexchange/ent/balance"
	"github.com/tauki/invoiceexchange/ent/invoice"
	"github.com/tauki/invoiceexchange/ent/issuer"
	"github.com/tauki/invoiceexchange/ent/predicate"
)

// IssuerQuery is the builder for querying Issuer entities.
type IssuerQuery struct {
	config
	ctx          *QueryContext
	order        []issuer.OrderOption
	inters       []Interceptor
	predicates   []predicate.Issuer
	withInvoices *InvoiceQuery
	withBalance  *BalanceQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IssuerQuery builder.
func (iq *IssuerQuery) Where(ps ...predicate.Issuer) *IssuerQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit the number of records to be returned by this query.
func (iq *IssuerQuery) Limit(limit int) *IssuerQuery {
	iq.ctx.Limit = &limit
	return iq
}

// Offset to start from.
func (iq *IssuerQuery) Offset(offset int) *IssuerQuery {
	iq.ctx.Offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *IssuerQuery) Unique(unique bool) *IssuerQuery {
	iq.ctx.Unique = &unique
	return iq
}

// Order specifies how the records should be ordered.
func (iq *IssuerQuery) Order(o ...issuer.OrderOption) *IssuerQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryInvoices chains the current query on the "invoices" edge.
func (iq *IssuerQuery) QueryInvoices() *InvoiceQuery {
	query := (&InvoiceClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issuer.Table, issuer.FieldID, selector),
			sqlgraph.To(invoice.Table, invoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, issuer.InvoicesTable, issuer.InvoicesColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBalance chains the current query on the "balance" edge.
func (iq *IssuerQuery) QueryBalance() *BalanceQuery {
	query := (&BalanceClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issuer.Table, issuer.FieldID, selector),
			sqlgraph.To(balance.Table, balance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, issuer.BalanceTable, issuer.BalanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Issuer entity from the query.
// Returns a *NotFoundError when no Issuer was found.
func (iq *IssuerQuery) First(ctx context.Context) (*Issuer, error) {
	nodes, err := iq.Limit(1).All(setContextOp(ctx, iq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{issuer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *IssuerQuery) FirstX(ctx context.Context) *Issuer {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Issuer ID from the query.
// Returns a *NotFoundError when no Issuer ID was found.
func (iq *IssuerQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = iq.Limit(1).IDs(setContextOp(ctx, iq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{issuer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *IssuerQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Issuer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Issuer entity is found.
// Returns a *NotFoundError when no Issuer entities are found.
func (iq *IssuerQuery) Only(ctx context.Context) (*Issuer, error) {
	nodes, err := iq.Limit(2).All(setContextOp(ctx, iq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{issuer.Label}
	default:
		return nil, &NotSingularError{issuer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *IssuerQuery) OnlyX(ctx context.Context) *Issuer {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Issuer ID in the query.
// Returns a *NotSingularError when more than one Issuer ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *IssuerQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = iq.Limit(2).IDs(setContextOp(ctx, iq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{issuer.Label}
	default:
		err = &NotSingularError{issuer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *IssuerQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Issuers.
func (iq *IssuerQuery) All(ctx context.Context) ([]*Issuer, error) {
	ctx = setContextOp(ctx, iq.ctx, "All")
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Issuer, *IssuerQuery]()
	return withInterceptors[[]*Issuer](ctx, iq, qr, iq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iq *IssuerQuery) AllX(ctx context.Context) []*Issuer {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Issuer IDs.
func (iq *IssuerQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if iq.ctx.Unique == nil && iq.path != nil {
		iq.Unique(true)
	}
	ctx = setContextOp(ctx, iq.ctx, "IDs")
	if err = iq.Select(issuer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *IssuerQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *IssuerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iq.ctx, "Count")
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iq, querierCount[*IssuerQuery](), iq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iq *IssuerQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *IssuerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iq.ctx, "Exist")
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *IssuerQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IssuerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *IssuerQuery) Clone() *IssuerQuery {
	if iq == nil {
		return nil
	}
	return &IssuerQuery{
		config:       iq.config,
		ctx:          iq.ctx.Clone(),
		order:        append([]issuer.OrderOption{}, iq.order...),
		inters:       append([]Interceptor{}, iq.inters...),
		predicates:   append([]predicate.Issuer{}, iq.predicates...),
		withInvoices: iq.withInvoices.Clone(),
		withBalance:  iq.withBalance.Clone(),
		// clone intermediate query.
		sql:  iq.sql.Clone(),
		path: iq.path,
	}
}

// WithInvoices tells the query-builder to eager-load the nodes that are connected to
// the "invoices" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *IssuerQuery) WithInvoices(opts ...func(*InvoiceQuery)) *IssuerQuery {
	query := (&InvoiceClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withInvoices = query
	return iq
}

// WithBalance tells the query-builder to eager-load the nodes that are connected to
// the "balance" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *IssuerQuery) WithBalance(opts ...func(*BalanceQuery)) *IssuerQuery {
	query := (&BalanceClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withBalance = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Issuer.Query().
//		GroupBy(issuer.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *IssuerQuery) GroupBy(field string, fields ...string) *IssuerGroupBy {
	iq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IssuerGroupBy{build: iq}
	grbuild.flds = &iq.ctx.Fields
	grbuild.label = issuer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Issuer.Query().
//		Select(issuer.FieldName).
//		Scan(ctx, &v)
func (iq *IssuerQuery) Select(fields ...string) *IssuerSelect {
	iq.ctx.Fields = append(iq.ctx.Fields, fields...)
	sbuild := &IssuerSelect{IssuerQuery: iq}
	sbuild.label = issuer.Label
	sbuild.flds, sbuild.scan = &iq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IssuerSelect configured with the given aggregations.
func (iq *IssuerQuery) Aggregate(fns ...AggregateFunc) *IssuerSelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *IssuerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iq); err != nil {
				return err
			}
		}
	}
	for _, f := range iq.ctx.Fields {
		if !issuer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *IssuerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Issuer, error) {
	var (
		nodes       = []*Issuer{}
		withFKs     = iq.withFKs
		_spec       = iq.querySpec()
		loadedTypes = [2]bool{
			iq.withInvoices != nil,
			iq.withBalance != nil,
		}
	)
	if iq.withBalance != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, issuer.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Issuer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Issuer{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withInvoices; query != nil {
		if err := iq.loadInvoices(ctx, query, nodes,
			func(n *Issuer) { n.Edges.Invoices = []*Invoice{} },
			func(n *Issuer, e *Invoice) { n.Edges.Invoices = append(n.Edges.Invoices, e) }); err != nil {
			return nil, err
		}
	}
	if query := iq.withBalance; query != nil {
		if err := iq.loadBalance(ctx, query, nodes, nil,
			func(n *Issuer, e *Balance) { n.Edges.Balance = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *IssuerQuery) loadInvoices(ctx context.Context, query *InvoiceQuery, nodes []*Issuer, init func(*Issuer), assign func(*Issuer, *Invoice)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Issuer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Invoice(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(issuer.InvoicesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.issuer_invoices
		if fk == nil {
			return fmt.Errorf(`foreign-key "issuer_invoices" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "issuer_invoices" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (iq *IssuerQuery) loadBalance(ctx context.Context, query *BalanceQuery, nodes []*Issuer, init func(*Issuer), assign func(*Issuer, *Balance)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Issuer)
	for i := range nodes {
		if nodes[i].issuer_balance == nil {
			continue
		}
		fk := *nodes[i].issuer_balance
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(balance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "issuer_balance" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (iq *IssuerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	_spec.Node.Columns = iq.ctx.Fields
	if len(iq.ctx.Fields) > 0 {
		_spec.Unique = iq.ctx.Unique != nil && *iq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *IssuerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(issuer.Table, issuer.Columns, sqlgraph.NewFieldSpec(issuer.FieldID, field.TypeUUID))
	_spec.From = iq.sql
	if unique := iq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iq.path != nil {
		_spec.Unique = true
	}
	if fields := iq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issuer.FieldID)
		for i := range fields {
			if fields[i] != issuer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *IssuerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(issuer.Table)
	columns := iq.ctx.Fields
	if len(columns) == 0 {
		columns = issuer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.ctx.Unique != nil && *iq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IssuerGroupBy is the group-by builder for Issuer entities.
type IssuerGroupBy struct {
	selector
	build *IssuerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *IssuerGroupBy) Aggregate(fns ...AggregateFunc) *IssuerGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the selector query and scans the result into the given value.
func (igb *IssuerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, igb.build.ctx, "GroupBy")
	if err := igb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IssuerQuery, *IssuerGroupBy](ctx, igb.build, igb, igb.build.inters, v)
}

func (igb *IssuerGroupBy) sqlScan(ctx context.Context, root *IssuerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*igb.flds)+len(igb.fns))
		for _, f := range *igb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*igb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IssuerSelect is the builder for selecting fields of Issuer entities.
type IssuerSelect struct {
	*IssuerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *IssuerSelect) Aggregate(fns ...AggregateFunc) *IssuerSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *IssuerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, "Select")
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IssuerQuery, *IssuerSelect](ctx, is.IssuerQuery, is, is.inters, v)
}

func (is *IssuerSelect) sqlScan(ctx context.Context, root *IssuerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
