// Code generated by mockery v2.14.1. DO NOT EDIT.

package bid

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	unitofwork "github.com/tauki/invoiceexchange/internal/unitofwork"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateBid provides a mock function with given fields: ctx, b, opts
func (_m *MockRepository) CreateBid(ctx context.Context, b *Bid, opts ...unitofwork.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, b)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Bid, ...unitofwork.Option) error); ok {
		r0 = rf(ctx, b, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBid provides a mock function with given fields: ctx, id, opts
func (_m *MockRepository) DeleteBid(ctx context.Context, id uuid.UUID, opts ...unitofwork.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...unitofwork.Option) error); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBidByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetBidByID(ctx context.Context, id uuid.UUID) (*Bid, error) {
	ret := _m.Called(ctx, id)

	var r0 *Bid
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Bid); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Bid)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBidsByInvestorID provides a mock function with given fields: ctx, investorID
func (_m *MockRepository) ListBidsByInvestorID(ctx context.Context, investorID uuid.UUID) ([]*Bid, error) {
	ret := _m.Called(ctx, investorID)

	var r0 []*Bid
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*Bid); ok {
		r0 = rf(ctx, investorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Bid)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, investorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBidsByInvoiceID provides a mock function with given fields: ctx, invoiceID, opts
func (_m *MockRepository) ListBidsByInvoiceID(ctx context.Context, invoiceID uuid.UUID, opts ...unitofwork.Option) ([]*Bid, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, invoiceID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*Bid
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...unitofwork.Option) []*Bid); ok {
		r0 = rf(ctx, invoiceID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Bid)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...unitofwork.Option) error); ok {
		r1 = rf(ctx, invoiceID, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBid provides a mock function with given fields: ctx, b, opts
func (_m *MockRepository) UpdateBid(ctx context.Context, b *Bid, opts ...unitofwork.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, b)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Bid, ...unitofwork.Option) error); ok {
		r0 = rf(ctx, b, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t mockConstructorTestingTNewMockRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
