// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Balance is the predicate function for balance builders.
type Balance func(*sql.Selector)

// Bid is the predicate function for bid builders.
type Bid func(*sql.Selector)

// Investor is the predicate function for investor builders.
type Investor func(*sql.Selector)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// InvoiceItem is the predicate function for invoiceitem builders.
type InvoiceItem func(*sql.Selector)

// Issuer is the predicate function for issuer builders.
type Issuer func(*sql.Selector)

// Ledger is the predicate function for ledger builders.
type Ledger func(*sql.Selector)
